export const userType = {
    FETCH_USER_REQUEST : "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS : "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE : "FETCH_USER_FAILURE"
  }


  export const signupType = {
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAILURE : "SIGNUP_FAILURE"
  }

  export const signinType = {
    SIGNIN_REQUEST : "SIGNIN_REQUEST",
    SIGNIN_SUCCESS : "SIGNIN_SUCCESS",
    SIGNIN_FAILURE : "SIGNIN_FAILURE"
  }



